### ISSUE TITLE
Cannot see edit or create operation UIs

### ISSUE THREAD

**Issue by zaheral** [ngx-meta/rules#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm not able to see the edit or create UIs, just the view UI. I followed theses steps:
* `ng new MyDetailPage --style=scss`
* y (for routing)
* `cd MyDetailPage/`
* `ng add @ngx-metaui/rules`
* n (for skipping npm install)
* select "fiori"
* `ng g  @ngx-metaui/rules:mPage --modelClass=User --name=UserDetail`
* select "fiori"
* `npm run compile:oss`
* replaced the "app.component.html" content with `<app-user-detail></app-user-detail>`
 * `ng serve`

Compilation works and I can see the Form in the view UI, but when I click on the edit or create view then the UI will be empty (besides the view, edit & create button) and I get the following error in the console:
```
core.js:5873 ERROR TypeError: Cannot read property 'disposables' of undefined
    at MetaIncludeDirective.applyNgModel (ngx-metaui-rules.js:13848)
    at MetaIncludeDirective.applyInputs (ngx-metaui-rules.js:13779)
    at MetaIncludeDirective.applyBindings (ngx-metaui-rules.js:13705)
    at MetaIncludeDirective.doRenderComponent (ngx-metaui-rules.js:12909)
    at MetaIncludeDirective.ngOnInit (ngx-metaui-rules.js:12844)
    at callHook (core.js:3937)
    at callHooks (core.js:3901)
    at executeInitAndCheckHooks (core.js:3842)
    at refreshView (core.js:11795)
    at refreshDynamicEmbeddedViews (core.js:13142)
```

## Expected behavior
See the edit/create UI

## Minimal reproduction of the problem with instructions
See at *Current behavior*

## What is the motivation / use case for changing the behavior?
Just learning

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 80.0.3987.122
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.17.0
- Platform:  Mac version 10.15.3

Others:

</code></pre>

**Comment by fkolar** [comment]
It looks like NG9 right ? 
I aware of this issue. There is #52. 

The thing behind this is that I am binding programatically Form API just like you would use [(ngModel)] and since Angular does not provide us any way to do this properly its more hackish way so in this case it fails. 

There is a existing work in progress and once its done, I am expected to work on this one. We want to have this NG9 compatible by the end of March.

**Comment by zaheral** [comment]
Hi @fkolar ,
thanks for the reply, but unfortunately I have now a different error after I changed the angular dependencies from 9.x.x to versions 8.x.x. Running `npm install` worked fine, but when I run `ng serve`, then I'm getting an error.

Here are my dependencies:
```
  "dependencies": {
    "@angular/animations": "~8.x.x",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.x.x",
    "@angular/compiler": "~8.x.x",
    "@angular/core": "~8.x.x",
    "@angular/forms": "~8.x.x",
    "@angular/platform-browser": "~8.x.x",
    "@angular/platform-browser-dynamic": "~8.x.x",
    "@angular/router": "~8.x.x",
    "@fundamental-ngx/core": "0.12.1-rc.9",
    "@fundamental-ngx/platform": "0.12.1-rc.9",
    "@ngx-metaui/fiori-rules": "^8.2.0",
    "@ngx-metaui/rules": "^8.2.0",
    "big-integer": "1.6.48",
    "flexboxgrid": "^6.3.1",
    "object-hash": "1.3.1",
    "object-path": "^0.11.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "typescript-collections": "1.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~8.x.x",
    "@angular/compiler-cli": "~8.x.x",
    "@angular/language-service": "~8.x.x",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5",
    "watch": "^1.0.2"
  }
```

Here are my:
```
[error] Error: Job name "..getProjectMetadata" does not exist.
    at Observable.rxjs_1.Observable [as _subscribe] (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)
    at Observable._trySubscribe (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at /Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/Users/.../MyDetailPage/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
```

**Comment by fkolar** [comment]
We had similar error internally. As Linked library called fundamentals style is aggresivelily evolving there could be some version mismatch. Our problem was it automatically instaled nex minor version of fundamentals styles library and it caused this issue. 

This should be quick fix, Currently working on upgrading this to latest version of fiori library and this should fix this issue. In meanwhile if you want to play with it you can use material lib instead.

**Comment by fkolar** [comment]
I double checked and it seems to work againts version 8 as expected. Version 9 support is on its way. 

Make sure that you are using angular cli v 8 too. What I see could happend that you run `npm install -g @angular/cli` which installed v9 as Angular just release v9 and all the dependencies took different path.

If you still want to play I recomend running:

```
npm install -g @angular/cli@8.3.25
ng add @ngx-metaui/rules (select fiori)
ng g  @ngx-metaui/rules:mPage --modelClass=User --name=UserDetail
...
```

Follow[ getting started](https://github.com/ngx-meta/rules/blob/master/GETTING-STARTED.md)...
